version: "3.7"
services:
  superset:
    image: robotic-docker.artifactory.cib.echonet/apache/superset:4.1.1
    container_name: superset
    restart: always
    ports:
      - "8088:8088"
    environment:
      SUPERSET_ENV: production
      SUPERSET_DATABASE_URI: postgresql+psycopg2://superset:superset@db:5432/superset
      REDIS_HOST: redis
    volumes:
      - superset_home:/app/superset_home
    depends_on:
      - db
      - redis
    command: >
      /bin/sh -c "
        superset db upgrade &&
        superset init &&
        superset run -h 0.0.0.0 -p 8088"
  
  db:
    image: robotic-docker.artifactory.cib.echonet/postgres:15
    container_name: superset-db
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
    volumes:
      - db_home:/var/lib/postgresql/data

  redis:
    image: robotic-docker.artifactory.cib.echonet/redis:7
    container_name: superset-redis
    restart: always

volumes:
  db_home:
  superset_home: